name: git pull on PETER-PRAGUE

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  pull:
    runs-on: self-hosted

    steps:
      - name: Pull repository from GitHub
        run: |
          cd C:\inetpub\wwwroot\gangnamstyle.dev
          git pull
        shell: cmd
