name: git pull on PETER-PRAGUE

on: 
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build-and-deploy:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3

    - name: Pull repository from GitHub
      run: |
        cmd
        cd C:\inetpub\wwwroot\gangnamstyle.dev
        git pull