name: git pull on ZEPHYR

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  pull:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Pull repository from GitHub
        run: |
          cd /var/www/flwn.dev/html
          git config --global --add safe.directory /var/www/flwn.dev/html
          git pull
